### ISSUE TITLE
Use external JS library

### ISSUE THREAD

**Issue by azurh** [square/duktape-android#104]
Hello,

Can I attach somehow and use external javascript libraries like `analytics.js` and `firebase.js` (from Google) with Duktape?

Thanks.

**Comment by JakeWharton** [comment]
Provided they don't require APIs that Duktape doesn't expose, sure.

**Comment by azurh** [comment]
Ok thanks, but how to do this with Duktape? Is there any exposed method which takes a .js file as an argument or something like this?

**Comment by JakeWharton** [comment]
No. You can load the JS into a string and execute it though.
