### ISSUE TITLE
Object.assign() crash

### ISSUE THREAD

**Issue by TizioIncognito** [square/duktape-android#110]
Executing the following javascript, I hava a duktape crash.
`val duktape = Duktape.create()`
`duktape.evaluate("var aa = {};    Object.assign({}, aa);")`

This is the stacktrace:
`06-11 14:08:26.391 13157-13543/com.example.jsduktape E/AndroidRuntime: FATAL EXCEPTION: Thread-7`
`    Process: com.example.jsduktape, PID: 13157`
`    com.squareup.duktape.DuktapeException: TypeError: undefined not callable`
`        at JavaScript.eval(?:1)`
`        at com.squareup.duktape.Duktape.evaluate(Native Method)`
`        at com.squareup.duktape.Duktape.evaluate(Duktape.java:69)`
`        at com.example.jsduktape.MainActivity$onCreate$1.run(MainActivity.kt:56)`
`        at java.lang.Thread.run(Thread.java:764)`

If I execute the same javascript on a WebView, there are no problems.

**Comment by JakeWharton** [comment]
`Object.assign` is not supported by Duktape (the upstream library) 1.x and was implemented in 2.0. You can follow #108 for when this library updates to track Duktape 2.x.
