### ISSUE TITLE
we wish to use duk_load_function

### ISSUE THREAD

**Issue by livrish** [square/duktape-android#113]
is this in the wrapper already ? if we want to enable it are there any considerations we need to be thinking about , any potential pitfalls etc

**Comment by szurbrigg** [comment]
It's not currently in the wrapper, and to be honest I'm not sure it's something I'd be interested in adding.  There's some mention of the dangers of using that method [here](http://duktape.org/api.html#duk_load_function).  

If you wanted to support it, you'd also need a way to marshal the raw bytes back and forth through the wrapper to Java - our implementation doesn't support `byte`/`byte[]`.

Just curious - what do you want to do?  Do you want to save re-compilation of the same code between threads?

**Comment by livrish** [comment]
This is a little off point but Its interesting that the documentation contradicts itself . 
https://github.com/svaarala/duktape/blob/master/doc/bytecode.rst
There are two main motivations for using bytecode dump/load:
- Performance
- Obfuscation
whereas where you pointed out "Duktape bytecode format is not intended for obfuscation"  
given that "the action of making something obscure, unclear, or unintelligible" i would argue that it is obfuscation

The reason I bring this up is that that is what we want to-do so I guess we would have to also look at signing the bytecode ? to ensure that it is safe.

**Comment by livrish** [comment]
is it faster to load from bytecode or the javascript i am also assuming that it is faster to load from bytecode than from javascript as well

**Comment by szurbrigg** [comment]
I haven't profiled it (the main goal of our wrapper isn't performance), but I would guess that loading from bytecode would be faster.
