### ISSUE TITLE
Is it possible to use this library as a webView ?

### ISSUE THREAD

**Issue by LaurentiuSimionescu** [square/duktape-android#118]
I want to parse website pages with normal webView, but it not suited for this.
I need something like okHttp requestTag, does Duktape allow this ? Can I use Duktape like a WebView (just for parsing and navigation in websites, no need to show the page on the screen) ?

Thanks in advance.

**Comment by JakeWharton** [comment]
It doesn't have APIs for things like the DOM, so traditional browser JS won't work. For that you need an actual browser to provide those APIs.

**Comment by LaurentiuSimionescu** [comment]
Thank you for the info.
