### ISSUE TITLE
Can duktape parse an object?

### ISSUE THREAD

**Issue by gabrielle88** [square/duktape-android#124]
The documentation say that "Object is supported in declarations, but the type of the actual value passed must be one of the above(boolean, int, double, string and void) or null." 
Is there any way to send an Object to js?

**Comment by JakeWharton** [comment]
No, but you can use an interface to expose its data to JS similar to https://github.com/square/duktape-android/#example

**Comment by JakeWharton** [comment]
Or serialize it as JSON and send it as a string and deserialize on the other side.

**Comment by gabrielle88** [comment]
These solutions will increase a lot the complexity on Android app and on Java script side. If I have for example a class Person(firstName:String, lastName:String) it would be great to have a possibility to send it as it is to js and js to know to interpret it.

**Comment by JakeWharton** [comment]
If you want to send data then serializing as JSON is likely your best bet.
