### ISSUE TITLE
FYI: another Android QuickJS implementation in the works

### ISSUE THREAD

**Issue by alastaircoote** [square/duktape-android#143]
I was very interested to see that you're working on replacing Duktape with QuickJS in the library. I'm very interested in using it so will try to get involved wherever I can. Just as an FYI, there's a work in progress here too:

https://github.com/seven332/quickjs-android

Just wondering if there is any opportunity for collaboration or code sharing there.

**Comment by JakeWharton** [comment]
It looks like that repo is supporting arbitrary objects crossing the bridge through a Moshi/Gson-like serialization mechanism? I think that's probably far more than we're likely to support. Although, secretly, I do have some plans that are not too dissimilar but will likely take a different approach.

They also appear to have an object model for JS values and we prefer to map directly to the language types.

I'm also not sure if there's an equivalent to our two-way binding feature.

I'm not opposed to sharing ideas and working with each other, but right now our feature sets seem somewhat incompatible in terms of reconciliation.

**Comment by koush** [comment]
@alastaircoote I have a heavily forked (to the point where it's been totally rewritten and should be renamed) version of duktape-android that supports quickjs:

https://github.com/koush/duktape-android

It supports duktape and quickjs (duktape to be removed probably, but its in there for legacy compat with some products i have).
It also supports:
 * debugging both javascript runtimes in vscode. (duktape has a debugger, I wrote one for QuickJS last week, it's in the marketplace)
 * marshalling java and javascript objects (not just interfaces) back and forth between the runtimes as return values and parameters.

In a private repo, I have polyfilled enough node/web APIs, that most npm libraries work without any futzing. axios, net, mdns, etc. I'll likely open source that as well.

**Comment by webfolderio** [comment]
@koush lots of new feature, thanks

Is it compatible with OpenJDK? I am asking this because duktape-android supports Dalvik not OpenJDK

**Comment by koush** [comment]
> @koush lots of new feature, thanks
> 
> Is it compatible with OpenJDK? I am asking this because duktape-android supports Dalvik not OpenJDK

Yes, part of the work was getting it working in a desktop/server environment. I build/test on Mac and deploy to android.

**Comment by alastaircoote** [comment]
@koush this looks amazing, and just what I was thinking of. Thank you so much, I'm going to have to take it for a spin!
