### ISSUE TITLE
And another duktape/quickjs implementation

### ISSUE THREAD

**Issue by oleksandr-yefremov** [square/duktape-android#145]
Hi guys, 
we have been using our extended version of Duktape Android internally for a while and recently added support for quickjs and open sourced it - https://github.com/prosiebensat-1-digital-gmbh/oasis-jsbridge

Basically we built things "on top of" duktape-android, so I think API should be very similar. What we added is:

* more type inference (using generics with reified parameters)
* support for suspending functions
* two-way support for JS promises (mapped to Deferred or suspending functions)
* JsValue type to refer arbitrary JS values
* a bit more memory handling code in JNI
* some JS runtime polyfills (setTimeout, XHR, console) and waiting for Duktape debugger VSCode plugin connection on client

QuickJS flavor has the same feature set (except for debugger). In case you are interested in bringing in these features into Duktape Android, we would be glad to consolidate the efforts and have one library instead of two :)

cc @bwalter

**Comment by swankjesse** [comment]
Neato!

Our approach to date has been to deliberately limit what you can do with this library. I’ve personally been anxious about the maintainability and performance drawbacks of hiding the boundary between JS and Java. If we make it too easy to write programs that mix the two languages, people might write such programs and those programs might have bad properties.

But the approach you’re taking is very nice. More power, but still very much honoring the fact that the memory JS sees is distinct from the memory Java sees.

I’m not ready to immediately consolidate. Our risk tolerance is low and ownership is difficult. But we’ll keep an eye on your project and perhaps even encourage users to check it out when they bump into the limits of what this library does for them.

**Comment by oleksandr-yefremov** [comment]
I totally understand that ownership question may be hard. Just want to say that we are pretty flexible in that regard.

> I’ve personally been anxious about the maintainability and performance drawbacks of hiding the boundary between JS and Java. If we make it too easy to write programs that mix the two languages, people might write such programs and those programs might have bad properties.

I am curious, what kind of drawbacks (except for obvious JS interpreter performance) do you have in mind? People can write bad and good programs with any tool. In this case it's visible what is crossing the bridge (Native->JS and JS->Native interfaces). We see the listed features as natural development of Duktape and I am trying to understand why you "deliberately limit what you can do with this library". Or maybe you just have another roadmap that @jakewharton hinted at here (https://github.com/square/duktape-android/issues/143#issuecomment-522201495)?

**Comment by swankjesse** [comment]
I'm anxious of architectural and maintainability problems. Not sure what, but it's a if departure from what I know works.
