### ISSUE TITLE
This code produces SyntaxError

### ISSUE THREAD

**Issue by holmium** [square/duktape-android#172]
for(var i = 0; i < 10; ++i)/[0-9]/.test("1")

    SyntaxError: parse error

Version: 1.3.0

Thanks!

**Comment by JakeWharton** [comment]
Hi! Please report this to the upstream [Duktape](https://duktape.org/) project. This is only a repackaging for Android use. Once they fix it, we'll pick it up in a new release.

**Comment by holmium** [comment]
> Hi! Please report this to the upstream [Duktape](https://duktape.org/) project. This is only a repackaging for Android use. Once they fix it, we'll pick it up in a new release.

OK.

Could you update to latest Duktape? It may have already fixed it. Although I don't have the environment to do a test.

**Comment by JakeWharton** [comment]
We're in the process of phasing out Duktape support in favor of QuickJS. I can take a look at updating, but it's unclear whether there will ever be another release with Duktape.

**Comment by JakeWharton** [comment]
Here's the latest update: #173

**Comment by holmium** [comment]
> Here's the latest update: #173

Thanks very much!
