### ISSUE TITLE
Call a Java functions from duktape

### ISSUE THREAD

**Issue by josdejong** [square/duktape-android#29]
It would be useful to be able to call native Java/Android functions from within JavaScript, similar to how Rhino allows [importing native functions](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Scripting_Java). 

For my specific case there is no need to implement full support for conversion between Java and JS objects, it would be enough to just be able to call a function with primitive arguments like double, String, int.

**Comment by JakeWharton** [comment]
I was messing with this a while ago. I wrote an API but not an implementation :grinning: 

```java
interface Math {
  int add(int one, int two);
}

// Bind a JS object to Java API.
Math math = duktape.proxy("math", Math.class);
```
```java
class Listener {
  void onSomething(String result) {
    System.out.println(result);
  }
}

// Bind a Java instance to a JS object.
duktape.bind("listener", new Listener());
```

**Comment by swankjesse** [comment]
This looks quite fun.

**Comment by josdejong** [comment]
That looks awesome! And much simpler than the API of Rhino.

**Comment by josdejong** [comment]
Any news on this?

**Comment by szurbrigg** [comment]
I'm hoping to get to this soon, likely in the next week or two.

**Comment by josdejong** [comment]
That's good news, thanks for the update!

**Comment by szurbrigg** [comment]
This has been implemented!

**Comment by josdejong** [comment]
Ah, that's cool! Thanks. Going to give it a try soon.

I found some example usages in the unit tests, looks easy to use. A bit of docs/examples would be welcome though.

**Comment by szurbrigg** [comment]
Absolutely, I'm updating the README next..

**Comment by josdejong** [comment]
I just fiddled around with this new feature, it works great, also gives back useful error stack traces. I really love the minimalist interface. Thanks!

Just as a side note: I worked a lot with rhino, which supports not only primitives but also passing Java classes as arguments and return types. In practice this works really painful though, and we ended up passing objects as stringified JSON. So... please just stick to support for primitives :).

One question: what is the reason that you only support a class interface? It would be convenient if you can also just pass a class I think.

**Comment by swankjesse** [comment]
We use an interface to discourage users from passing arbitrary types like `ArrayList` or `BigInteger`. We want the types shared between Java and JavaScript to be designed specifically for that purpose.

**Comment by josdejong** [comment]
That makes sense, thanks for the explanation.
