### ISSUE TITLE
No static method with name='getLocalTimeZoneOffset' signature='(D)I'

### ISSUE THREAD

**Issue by jeffskla** [square/duktape-android#30]
With 0.9.3 or 0.9.4, I get:

java.lang.NoSuchMethodError: no static method with name='getLocalTimeZoneOffset' signature='(D)I' in class Lcom/squareup/duktape/Duktape;

0.9.1 is fine. I am targeting API 19.

**Comment by swankjesse** [comment]
Did you rebuild the binaries?

**Comment by jeffskla** [comment]
I'm including the published binaries in my build.gradle.

**Comment by swankjesse** [comment]
This looks like a mismatch between the native libraries and the Java libraries in your project. Maybe you're getting two copies of duktape-android?

**Comment by jeffskla** [comment]
No, this turned out to be Proguard stripping that method out because it isn't used in java code. Adding this to proguard-keep.txt fixed the issue:

   -keep class com.squareup.duktape.** { *; }

**Comment by swankjesse** [comment]
ProGuard!
