### ISSUE TITLE
Support returning double and boolean from evaluate 

### ISSUE THREAD

**Issue by josdejong** [square/duktape-android#44]
The return value of `duktape.evaluate` returns `null` when not a string:

```java
duktape.evaluate("2 + 3"); // returns null
```

This is a bit tricky if you're not aware of it.

It would be great when `evaluate` would also allow returning primitives like `double` and `boolean`, maybe like this:

```java
Double result = duktape.evaluate("2 + 3", Double.class);
```

**Comment by swankjesse** [comment]
We’ll implement this in a type safe way as a part of https://github.com/square/duktape-android/issues/43

**Comment by josdejong** [comment]
Thanks!

**Comment by szurbrigg** [comment]
#43 is implemented.  Also, Duktape.evaluate now coerces the result to string, so

> `duktape.evaluate("2 + 3"); `

returns the String `"5"`.

**Comment by josdejong** [comment]
Great news, thanks!

**Comment by HugoGresse** [comment]
how are you returning a Double instead of a String? I can't find anything in the doc
