### ISSUE TITLE
Accept JavaScript callbacks as arguments?

### ISSUE THREAD

**Issue by ntrrgc** [square/duktape-android#61]
Is there a way to invoke JavaScript callbacks from Java? 

You would need that for asynchronous tasks (e.g. `setTimeout()` o reading network without blocking).

**Comment by szurbrigg** [comment]
Hmm... I think the best way to do that currently is to define a global JS object with a method that calls the desired callback, then use the `Duktape.proxy()` method to create an object that can be called from Java.  You could also use the evaluate method to invoke the callback directly: `Duktape.evaluate("setTimeout(10)");`  

We don't provide a way to call a free (non-member) function from Java.

**Comment by twhit093** [comment]
@ntrrgc did you end up finding a good way to implement setTimeout?

**Comment by ntrrgc** [comment]
@twhit093 No, I ended up rolling my own JavaScript bridge for Android that allows holding references to JS objects from Java (including functions) and therefore capable of these things. https://github.com/ntrrgc/jsvm
