### ISSUE TITLE
Get and set values to context

### ISSUE THREAD

**Issue by pietrocaselani** [square/duktape-android#63]
Are there any plans to implement methods to get and set values (variables and functions) on a duktape context?
I need to get a javascript function from Java code and invoke it with arguments?
Do you guys plan to do this soon? Otherwise I could open a pull request.

**Comment by szurbrigg** [comment]
We weren't planning anything like that.   Can you accomplish what you need with `Duktape.evaluate()`?  It can be used to set/get JS variables.

**Comment by pietrocaselani** [comment]
I need to do something like that.
```javascript
function hello(name) {
  return "Hello " + name;
}
```

And then in Java code

```java
helloFunction = duktape.get("hello");
helloFunction.call("World");
```

I can do this on iOS/JavaScriptCore with this [method](https://developer.apple.com/reference/javascriptcore/jsvalue/1451648-call).

**Comment by szurbrigg** [comment]
I've added a test that demonstrates how to do this with `Duktape.set` in https://github.com/square/duktape-android/pull/65.
