### ISSUE TITLE
Date can't be parsed

### ISSUE THREAD

**Issue by zenanhu** [square/duktape-android#77]
`new Date('2013/01/01')`
'2013/01/01' can't be parsed.

Could you support some normal date format? 
https://github.com/svaarala/duktape/issues/712

**Comment by szurbrigg** [comment]
We can add a method like `Duktape.setDateFormat(DateFormat format)` to allow the caller to override the default parser and formatter.

**Comment by zenanhu** [comment]
Thanks! And will next version(1.0.1) include these code?

**Comment by swankjesse** [comment]
I don't know if this makes sense. Is there a pure JavaScript way to do this?

**Comment by zenanhu** [comment]
Should duktape support these constructor?
[http://www.w3schools.com/js/js_date_formats.asp](url)

**Comment by zenanhu** [comment]
Any news?

**Comment by szurbrigg** [comment]
Sorry, haven't had a chance to look at this yet.  Will try to get something this week.

**Comment by sol-liu** [comment]
Hi Shawn, is there any update on this?

**Comment by szurbrigg** [comment]
A fix is in progress: https://github.com/square/duktape-android/pull/80

**Comment by szurbrigg** [comment]
Fixed in https://github.com/square/duktape-android/pull/80
