### ISSUE TITLE
String.fromCharCode wrong result

### ISSUE THREAD

**Issue by FD-** [square/duktape-android#79]
It seems String.fromCharCode returns wrong results, or at least they differ from other JS engines.
Calling String.fromCharCode(65) returns a strange symbol instead of the expected 'A'.

Is this expected behaviour, a Duktape issue or related to the Java wrapper?

**Comment by szurbrigg** [comment]
Is there something special about the way you're calling the function?

This works fine:
`    assertThat(duktape.evaluate("String.fromCharCode(65);")).isEqualTo("A");
`

**Comment by FD-** [comment]
I'm sorry, the issue didn't stem from Duktape, I really should have tested more carefully.
I did not realise the Charcode I passed was actually a String, not a Number. I integrate the other JS engines slightly differently, so I passed a Number there. With a string, all engines lead to Duktape's result.

Thanks for your awesome Duktape wrapper!
