### ISSUE TITLE
Rhino over Duktape

### ISSUE THREAD

**Issue by HugoGresse** [square/duktape-android#82]
Hi,

I was searching for a JS engine for Android and it seems that Rhino is ~10% more efficient than Duktape. What do you think about it? Maybe a real benchmark could be helpful...

**Comment by swankjesse** [comment]
Please do! Benchmarking on Android would be particularly useful since Rhino relies on the host VM whereas Duktape doesn’t.

I doubt we’d switch regardless of the numbers because we’re optimizing for compactness and not throughput.

**Comment by HugoGresse** [comment]
for what I see, runing 1000x the same operation which is creating a js function that return 1 and calling it and counting the return value in java, so the whole java > js > java chain is 10% faster using Rhino. What's more, Rhino is 600ko once packaged, Duktape is 2mB. To finish, Rhino is java based, no JNI which reduce the crash potential drastically. 

**DUKTAPE**
```
    public DuktapeTest(Listener listener, int loopNumber, Context context) {
        super(listener, loopNumber, context);

        mDuktape = Duktape.create();

        mDuktape.evaluate(COMMAND);


        long before = System.nanoTime();
        int result = 0;

        try {
            for(int i = 0; i < mLoopNumber; i++){
                result += test();
            }
        } finally {
            mDuktape.close();
        }

        if(result != mLoopNumber) {
            Log.w("Duktape", "Error loop end not reached correctly");
            super.onResult(-1);
            return;
        }

        super.onResult(System.nanoTime() - before);
    }

    private double test(){
        return Double.parseDouble(String.valueOf(mDuktape.evaluate("runTest()")));
    }
```

**RHINO**
```
    org.mozilla.javascript.Context mJSContext;

    public RhinoJarTest(Listener listener, int loopNumber, Context context) {
        super(listener, loopNumber, context);

        mJSContext = org.mozilla.javascript.Context.enter();

        mJSContext.setOptimizationLevel(-1);

        Scriptable scope = mJSContext.initStandardObjects();

         mJSContext.evaluateString(scope, "function runTest() { return 1; }", "ScriptAPI", 1, null);

        long before = System.nanoTime();
        int result = 0;

        try {
            for(int i = 0; i < mLoopNumber; i++){
                result += test(scope);
            }
        } finally {
            org.mozilla.javascript.Context.exit();
        }

        if(result != mLoopNumber) {
            Log.w("Rhino", "Error loop end not reached correctly");
            super.onResult(-1);
            return;
        }

        super.onResult(System.nanoTime() - before);
    }

    private double test(Scriptable scope){
        return Double.parseDouble(String.valueOf(mJSContext.evaluateString(scope, "runTest()", "ScriptAPI", 1, null)));
    }
```

**Comment by swankjesse** [comment]
Neat! Which OS / device? Mind providing the specific numbers? Also what's the time elapsed to run a single operation?

**Comment by swankjesse** [comment]
(I’m concerned about the potential time to initialize the JS engine. The 10% faster thing means less if it's 20% slower to initialize!)

**Comment by HugoGresse** [comment]
I'll probably publish a repo with the benchmarks (how to execute JS in Android). Anyways, [here](https://www.dropbox.com/s/0i78wm7ulfjnhw6/device-2016-12-09-151814.png?dl=0) is a result. I should probably run some real average on the result and complete the JS code with real calculation (not just returning values). Anyways, the [AndroidJSCore](https://github.com/ericwlange/AndroidJSCore) is pretty bad.

**Comment by HugoGresse** [comment]
It didn't count the initialize time, but based on my eye duktape and Rhino initialize time are pretty correct compared to webview for example.

**Comment by swankjesse** [comment]
Cool. Looking forward to seeing your repo with benchmarks.
