### ISSUE TITLE
Add support better for Java interoperability

### ISSUE THREAD

**Issue by ursusursus** [square/duktape-android#84]
Add support for being able to call arbitrary java class on classpath, like Rhino does (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Scripting_Java)

example js
```
function run(androidContext) {
     var FooActivity = Packages.com.example.FooActivity;
     var Intent = Packages.android.content.Intent;

     var intent = new Intent(androidContext, FooActivity);
     androidContext.startActivity(intent);
}
```

**Comment by NitroXenon** [comment]
:+1:

**Comment by swankjesse** [comment]
This makes more sense for Rhino than it does for Duktape. With Rhino there’s a single shared heap so you can share objects between JS and Java. But in Duktape JavaScript lives in a private sandbox and you can’t share objects with Java.

I consider this a feature – you can’t call `System.exit()` from JavaScript or take other potentially destructive actions. It means that Duktape JavaScript is limited, self-contained, and easy to reason about from a security perspective.

**Comment by ursusursus** [comment]
Please could you provide pointers as to how to make it possible if I were to fork it? Or is it by design impossible? Thanks

**Comment by swankjesse** [comment]
You’re on your own. Remember that in our Duktape model you can’t share objects with Java; you have to copy them.

**Comment by ursusursus** [comment]
I am just wondering if it is possible to have objects shared, since i presume duktape lives in C therefore in native memory, not java heap
