### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no duktape in java.library.path

### ISSUE THREAD

**Issue by allnex** [square/duktape-android#89]
Hello. I made some JUnit tests and I get this error when testing the Duktape methods I've made.

I don't get any error when building the android application, but when testing. I need to test to know if it works as excepted.

I tried including `System.getProperties()["java.library.path"] = "${System.getProperty("user.dir")}\\build\\"` in the same test, and `System.getProperty("java.library.path")` returns the excepted value.

**Comment by szurbrigg** [comment]
That's strange.  Are you able to run the other unit tests in the project (DuktapeTest, DuktapeGetTest, DuktapeSetTest)?
