### ISSUE TITLE
JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by sabinroman** [square/duktape-android#90]
I have setup a very simple bridge for the Foo interface, then tried to go through the bridge 1000 times in a for loop from JS to Java:

```
// 'foo' is a Ducktape bridged object. Java: duktape.set("foo", FooExport.class, foo);
for (var i = 0; i < 1000; i++) {
    var hello = foo.say('hello');
}
```
I get:
<img width="453" alt="screen shot 2017-06-01 at 7 01 18 pm" src="https://cloud.githubusercontent.com/assets/5128845/26691452/696ccc62-46fd-11e7-940a-4b4cb991c650.png">

I am trying to build a layer on top of Duktape to help bridge around more complex Objects. For this, a lot of calls to and from native are needed. The limitation of the reference table to 512 entries for each evaluate(..) call is really not enough.

I guess you should clean the references on the Native side immediately after the String result was returned to JS, and not wait until the evaluate() function has finished execution.

Did the same test within a WebView, and the issue did not appear.

Is this a known issue, is there any workaround?

**Comment by szurbrigg** [comment]
Thanks for the report - this was not a known issue.  I'll have a fix shortly.

**Comment by sabinroman** [comment]
Thanks for the super fast response and fix!

**Comment by szurbrigg** [comment]
https://github.com/square/duktape-android/pull/91

**Comment by resengupta** [comment]
I have a similar issue, Need some help here:

JNI ERROR (app bug): local reference table overflow (max=512)
    art/runtime/indirect_reference_table.cc:132] local reference table dump:
    art/runtime/indirect_reference_table.cc:132]   Last 10 entries (of 512):
    art/runtime/indirect_reference_table.cc:132]       511: 0x134f6250 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]       510: 0x134f6220 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]       509: 0x134f61f0 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]       508: 0x134f61c0 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]       507: 0x134f6190 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]       506: 0x134f6160 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]       505: 0x134f6130 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]       504: 0x134f6100 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]       503: 0x134f60d0 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]       502: 0x134f60a0 libcore.util.ZoneInfo
    art/runtime/indirect_reference_table.cc:132]   Summary:
    art/runtime/indirect_reference_table.cc:132]         2 of $Proxy21 (1 unique instances)
    art/runtime/indirect_reference_table.cc:132]         2 of $Proxy20 (1 unique instances)
    art/runtime/indirect_reference_table.cc:132]         1 of java.lang.Thread
    art/runtime/indirect_reference_table.cc:132]         2 of java.lang.reflect.Method (2 unique instances)
    art/runtime/indirect_reference_table.cc:132]         4 of java.lang.String (2 unique instances)
    art/runtime/indirect_reference_table.cc:132]         1 of java.util.ArrayList
    art/runtime/indirect_reference_table.cc:132]         1 of java.lang.Object[] (1 elements)
    art/runtime/indirect_reference_table.cc:132]         1 of java.lang.Object[] (2 elements)
    art/runtime/indirect_reference_table.cc:132]       498 of libcore.util.ZoneInfo (498 unique instances)


I getting the above error when i am using

> get(final String name, final Class<T> type)

the `type` interface is this:
```
  interface JsBinder {

        fun androidWrapper(functionName: String, **input**: String): String

    }
```

the String `**input**` in the interface is an Array of 44 objects.
