### ISSUE TITLE
Duktape error when build

### ISSUE THREAD

**Issue by KevinOfNeu** [square/duktape-android#92]
JNI error:
`/Users/***/Workspace/github/duktape-android/duktape/src/main/jni/duktape-jni.cpp
Error:(77, 20) error: use of undeclared identifier 'timegm'; did you mean 'time'?
Error:(77, 27) error: cannot initialize a parameter of type 'time_t *' (aka 'long *') with an rvalue of type 'tm *'`

**Comment by szurbrigg** [comment]
Hmm, this looks like a compile error.  What version of the NDK are you using?

**Comment by KevinOfNeu** [comment]
@szurbrigg 12

**Comment by szurbrigg** [comment]
Sorry, that's too old.  Please use 13b or higher.
