### ISSUE TITLE
How does it compare to LiquidCore or other similar projects?

### ISSUE THREAD

**Issue by letitfly** [square/duktape-android#94]
In terms of start time time, executing time, cross platform support?

https://github.com/LiquidPlayer/LiquidCore

**Comment by JakeWharton** [comment]
iOS has JavaScriptCore and the web has always been a native JavaScript VM
so there's no need for cross platform support in Duktape (and it's not like
that library offers cross platform support anyway).

Duktape is about 100x smaller than LiquidCore, so there's that.

There's no real startup time, but parsing and execution depends on what JS
you're running and you'll have to measure those things for yourself.

**Comment by letitfly** [comment]
That's the info I am looking for.  Thank you!
