### ISSUE TITLE
local reference table overflow (max=512) error

### ISSUE THREAD

**Issue by jeonhoeun** [square/duktape-android#95]
when I call duktape.set ("someName" , interface.class, interface instance ); 

local reference table overflow (max=512) error occured

interface method has 40 methods.

and if I set method count 30, the error is not occured.

so I'm call set two interface.class.

the first interface has 20 methods. and second interfacde has 20 method. 

Is it a bug?

**Comment by jeonhoeun** [comment]
error position is 
DuktapeContext.cpp
void DuktapeContext::set(JNIEnv *env, jstring name, jobject object, jobjectArray methods) {
 ....
 ....
 for( jsize i=0; i< numMethods; ++i){
   ...
  //here
  const JString methodName(env, static_cast<jstring>(env->CallObjectMethod(method, getName))); 
 ....
 }
 ...

**Comment by szurbrigg** [comment]
Yes, this is a bug.  Thanks for the report!

**Comment by jeonhoeun** [comment]
Execuse me..
I'm making a apps which using duktape android^^;...
Can I know that your team made a plan to fix this bug?

**Comment by szurbrigg** [comment]
A fix is in progress: https://github.com/square/duktape-android/pull/97.  I'll try to get a release out in the next week or two.

**Comment by szurbrigg** [comment]
Fixed.

**Comment by jeonhoeun** [comment]
Thank you for it.
Now it works very well~
