### ISSUE TITLE
How to run js method  with params

### ISSUE THREAD

**Issue by plaichat1986** [square/duktape-android#96]
If in java application, run js method in java, can send some params such as text or code,but i can't find any type to set params in using duktape.evaluate.
For Example
ScriptEngineManager engineManager = new ScriptEngineManager();
            ScriptEngine engine = engineManager.getEngineByName("JavaScript");
            engine.eval(new java.io.FileReader("test.js"));
            Invocable inv = (Invocable)engine;
            Object a = inv.invokeFunction("get", text, code);

**Comment by szurbrigg** [comment]
To pass parameters to a JS method, you can bind a JS object to a Java interface: https://github.com/square/duktape-android#calling-javascript-from-java.
