### ISSUE TITLE
Version 1.2.0 lib size

### ISSUE THREAD

**Issue by awenger** [square/duktape-android#99]
It looks like the size of the library increased quite significantly with the latest release (1.2.0). Is this by intention or did something go wrong during the build?

https://mvnrepository.com/artifact/com.squareup.duktape/duktape-android/1.1.0 (1.9 MB)
https://mvnrepository.com/artifact/com.squareup.duktape/duktape-android/1.2.0 (11.2 MB)

**Comment by szurbrigg** [comment]
Definitely a surprise.  Will take a look.

**Comment by szurbrigg** [comment]
Looks kind of like this https://github.com/android-ndk/ndk/issues/243.

**Comment by vaigunth** [comment]
Facing the same issue. Could you please fix it? It increased the APK size by 2x.

**Comment by szurbrigg** [comment]
After https://github.com/square/duktape-android/pull/105, the 1.3.0-SNAPSHOT is back down to 1.9MB.
